[pytest]
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    tdd: TDD tests
    bdd: BDD tests
    mock: Tests with mocks
    integration: Integration tests
